### ISSUE TITLE
bug: Edit Pack --> Quantity not showing

### ISSUE THREAD

**Issue by nordmanbp** [Packstack-Tech/packstack#105]
Checked in Chrome & Edge - when editing / creating a pack, the "qty" shows, but add/subtract arrows are nearly hidden except onmouseover, but the actual # is completely hidden. Probably a little glitch now that manufacturer field is displayed :-)

![pack_quantity](https://user-images.githubusercontent.com/83029884/150362722-824875c4-52e6-4a09-8d00-47fc57bc685e.png)

**Comment by smostertdev** [comment]
I am seeing this too. Pretty sure it's related to this:
https://github.com/Packstack-Tech/packstack/blob/69415fe0fc92ccd96cde51406394cb61606e725f/src/app/components/PackItems/Item.tsx#L59

When `item.manufacturer` is not defined it creates an empty 70px div

**Comment by maplethorpej** [comment]
Fixed
