### ISSUE TITLE
No "nice" way to return from pack View page

### ISSUE THREAD

**Issue by Callisto13** [Packstack-Tech/packstack#75]
This is a nit, but the experience is quite clunky:

- I am on my Packs page
- I click to view my pack
- I am taken to that page
- There are 2 ways to get back to my "userspace"
  -  click the browser back button
  - click the Packstack logo (this takes me back to the login page)

Again, just a small nit, but I feel people don't really expect to have to use the browser button with modern UIs, and going back to login (even if it does not log me out) is not ideal.

**Comment by maplethorpej** [comment]
I agree. I've moved the pack view page to another domain, which makes it tricky to have an optimal "back" option.

As a workaround, I think I'll have the pack view open in another tab. At least the user won't be moved out of the app in this case.

**Comment by Callisto13** [comment]
👍 that workaround sounds good
