### ISSUE TITLE
Configuring web application icon

### ISSUE THREAD

**Issue by via-justa** [Packstack-Tech/packstack#81]
When saving a link to packstack.io to home on iOS the site logo is missing.
Adding support for that require only adding `apple-touch-icon.png` on the site root folder as described [here](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

I think it's a fast win that should not be hard to implement and would be a very nice addition.

**Comment by maplethorpej** [comment]
Thanks for the heads up! I'll get that added
