### ISSUE TITLE
Enhancement: pack view page and pack edit/inventory pages are not consistent

### ISSUE THREAD

**Issue by via-justa** [Packstack-Tech/packstack#82]
While the inventory and pack edit pages got a max-width and are centralized, the pack view page does not. I'm using an ultrawide screen and the pack view page is very hard to work with when it's using the entire screen.

I think that the pack view page should have max-width and be centered as well if only for cross-site consistency

**Comment by maplethorpej** [comment]
Agreed. I'll set a reasonable max-width for pack view pages and will keep this in mind when updating the layout for editing packs too.
